INSERT INTO AIRPLANE (model) VALUES ('XXXX');
INSERT INTO AIRPLANE (model) VALUES ('A380');
INSERT INTO AIRPLANE (model) VALUES ('B747');
INSERT INTO AIRPLANE (model) VALUES ('B777');
INSERT INTO AIRPLANE (model) VALUES ('A340');
INSERT INTO AIRPLANE (model) VALUES ('A330');
INSERT INTO AIRPLANE (model) VALUES ('B737');
INSERT INTO AIRPLANE (model) VALUES ('A320');
INSERT INTO AIRPLANE (model) VALUES ('A319');
INSERT INTO AIRPLANE (model) VALUES ('A319');

INSERT INTO COLOR (color_name) VALUES ('Red');
INSERT INTO COLOR (color_name) VALUES ('Blue');
INSERT INTO COLOR (color_name) VALUES ('Yellow');
INSERT INTO COLOR (color_name) VALUES ('Pink');
INSERT INTO COLOR (color_name) VALUES ('Purple');
INSERT INTO COLOR (color_name) VALUES ('Orange');
INSERT INTO COLOR (color_name) VALUES ('Green');
INSERT INTO COLOR (color_name) VALUES ('Black');
INSERT INTO COLOR (color_name) VALUES ('White');
INSERT INTO COLOR (color_name) VALUES ('Gray');
INSERT INTO COLOR (color_name) VALUES ('Lightblue');
INSERT INTO COLOR (color_name) VALUES ('Multicolor');

INSERT INTO BAGCART_BRAND (brand) VALUES ('TLD JET-16');
INSERT INTO BAGCART_BRAND (brand) VALUES ('TLD JST-20');
INSERT INTO BAGCART_BRAND (brand) VALUES ('TLD JST-25');

INSERT INTO BAGCART (brand_id, year, seal) VALUES (1, 2010, 'FALSE');
INSERT INTO BAGCART (brand_id, year, seal) VALUES (1, 2012, 'FALSE');
INSERT INTO BAGCART (brand_id, year, seal) VALUES (2, 2003, 'FALSE');
INSERT INTO BAGCART (brand_id, year, seal) VALUES (3, 2014, 'FALSE');
